#!/bin/bash

set -e

if [[ -n "${DOCKERCFG}" ]]; then
  echo "${DOCKERCFG}" > /root/.dockercfg
  unset DOCKERCFG
fi

echo "--- starting ssh-agent"
eval "$(ssh-agent -s)"

echo "--- adding default keys"
ssh-add
